Fixed #364 - Replaced Bootstrap 3 by Bootstrap 4.
Bouke/django-two-factor-auth pull request #379
Opened 2020-08-20 16:34 UTC by claudep

I did my best to migrate Bootstrap classes. Might be worth double-checking the result.

2020-08-20 16:48 UTC, moggers87 commented on example/templates/_base.html
> +                {% if user.otp_device %}<i class="fa fa-lock"></i>{% endif %}
Is Font Awesome bundled with Bootstrap 4? Does Font Awesome provide a CDN for us to use?

Alternatively: there's a lock icon in Unicode that could be used instead.

2020-08-20 16:51 UTC, claudep commented on example/templates/_base.html
> +                {% if user.otp_device %}<i class="fa fa-lock"></i>{% endif %}
I considered the lock icon Unicode, but it looks like not very widely supported by common fonts. Did you experiment it?

And no, Font Awesome is not bundled.

2020-08-27 15:32 UTC, claudep commented on example/templates/_base.html
> +                {% if user.otp_device %}<i class="fa fa-lock"></i>{% endif %}
I replaced the Font Awesome tag by the Unicode version of the character.

2020-09-19 11:32 UTC, mathiasertl commented
@claudep I have run the merged PR and think it's fine. LGTM!

2020-09-21 18:40 UTC, moggers87 requested changes
Hey it's only been a month since you opened this PR :tada: 

Looks fine for the most part, there's only one thing that bugs me:

Bootstrap 3 navbar:
![Boostrap 3 with a gap under the nav](https://user-images.githubusercontent.com/1490673/93806964-e0a1df00-fc41-11ea-93be-da4bb35822f3.png)

Bootstrap 4 navbar, notice the lack of spacing between it and the page content:
![Boostrap 4 with no gap under the nav](https://user-images.githubusercontent.com/1490673/93806997-f0212800-fc41-11ea-8c83-b5863d715e09.png)

I don't know whether this is the new default or if there needs to be change in the markup to give the navbar some margin underneath, but it really sticks out to me as if it was a mistake either way.

2020-09-26 13:10 UTC, claudep commented
Indeed, `.navbar` has a margin bottom of 20px on BS3, and none on BS4. If you'd like to keep that spacing, we can simply add a `mb-3` style to the navbar to get a similar result.

2020-09-28 22:07 UTC, moggers87 commented
Much better. I'm chalking up any remaining "it looks weird" to me not being used to Boostrap 4 :stuck_out_tongue_winking_eye:

2020-09-28 22:07 UTC, moggers87 approved these changes

2020-09-28 22:08 UTC, merged